Resources:
  noteTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: notes
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: noteId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: noteId
          AttributeType: S
